name: Run Pytest workflow
on: [push]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install -r requirements.txt
      - run: pytest --cov -v
